wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.8
epochs:
  desc: null
  value: 12
n_hidden_units:
  desc: null
  value: 32
